app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), index=True)
    email = db.Column(db.String(255), unique=True, index=True)
    pass_secure = db.Column(db.String(255))
    subscription = db.Column(db.Boolean)
    date_joined = db.Column(db.DateTime, default=datetime.utcnow)


    posts = db.relationship('Post', backref='post', lazy="dynamic")
    comments = db.relationship('Comment', backref='user', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)

    def __repr__(self):
        return f'User {self.username}'


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))

    def __repr__(self):
        return f'User {self.name}'


class Post(db.Model):
    __tablename__ = 'posts'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String())
    text = db.Column(db.String())
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    date_posted = db.Column(db.DateTime, default=datetime.utcnow)
    comments = db.relationship('Comment', backref='post_id', lazy='dynamic')

    def save_post(self):
        db.session.add(self)
        db.session.commit()

    def get_post(id):
        post = Post.query.filter_by(id=id).first()
        return post


class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String(1000))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    post = db.Column(db.Integer, db.ForeignKey('posts.id'))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls, post):
        comments = Comment.query.filter_by(post=post.id).all()
        return comments

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField
from wtforms.validators import Required


class PostForm(FlaskForm):
    title = StringField('Title', validators=[Required()])
    text = TextAreaField('Blog Content', validators=[Required()])
    submit = SubmitField('Post', validators=[Required()])


class CommentForm(FlaskForm):
    text = TextAreaField('Leave a comment:', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_simplemde import SimpleMDE

bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()
simple = SimpleMDE()
photos = UploadSet('photos', IMAGES)

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

     #configuring a screat key
    app.config['SECRET_KEY'] = 'payoneer'

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    # configure UploadSet
    configure_uploads(app, photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template, request, redirect, url_for, abort
from . import main
from ..models import User, Post, Comment
from .. import db
from .forms import PostForm, CommentForm
from flask_login import login_required, current_user
import datetime
from ..email import mail_message
# from ..requests import get_quote


#Views


@main.route('/')
def index():
    '''
    View root page function that returns the index page and its data
    '''
    posts = Post.query.order_by(Post.date_posted.desc()).limit(3).all()
    # quote = get_quote()

    title = 'Home - Welcome to Payonner Blogger'

    return render_template('index.html', title=title, posts=posts)


@main.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    post_form = PostForm()
    if post_form.validate_on_submit():
        title = post_form.title.data
        text = post_form.text.data

        users = User.query.all()

        # Update the post instance
        new_post = Post(title=title, text=text, post=current_user)

        # Save post method
        new_post.save_post()
        return redirect(url_for('.index'))

        # for user in users:
        #     if user.subscription:
        #         mail_message("New Post", "email/new_post",
        #                         user.email, user=user)

        # return redirect(url_for('.index'))

    # else:
    #     return redirect(url_for('.index'))

    title = 'New post'
    return render_template('new_post.html', title=title, post_form=post_form)


@main.route('/posts')
def all_posts():
    posts = Post.query.order_by(Post.date_posted.desc()).all()

    title = 'Payoneer Blogger Posts'

    return render_template('posts.html', title=title, posts=posts)


@main.route('/post/<int:id>', methods=['GET', 'POST'])
def post(id):
    form = CommentForm()
    post = Post.get_post(id)

    if form.validate_on_submit():
        comment = form.text.data

        new_comment = Comment(comment=comment, user=current_user, post=post.id)

        new_comment.save_comment()

    comments = Comment.get_comments(post)

    title = f'{post.title}'
    return render_template('post.html', title=title, post=post, form=form, comments=comments)


@main.route('/delete_comment/<id>/<post_id>', methods=['GET', 'POST'])
def delete_comment(id, post_id):
    comment = Comment.query.filter_by(id=id).first()

    db.session.delete(comment)
    db.session.commit()

    return redirect(url_for('main.post', id=post_id))


@main.route('/delete_post/<id>', methods=['GET', 'POST'])
def delete_post(id):
    post = Post.query.filter_by(id=id).first()

    db.session.delete(post)
    db.session.commit()

    return redirect(url_for('main.all_posts'))


@main.route('/subscribe/<id>')
def subscribe(id):
    user = User.query.filter_by(id=id).first()

    user.subscription = True

    db.session.commit()

    return redirect(url_for('main.index'))


@main.route('/post/update/<id>', methods=['GET', 'POST'])
def update_post(id):
    form = PostForm()

    post = Post.query.filter_by(id=id).first()

    form.title.data = post.title
    form.text.data = post.text

    if form.validate_on_submit():
        title = form.title.data
        text = form.text.data

        post.title = title
        post.text = text

        db.session.commit()

        return redirect(url_for('main.post', id=post.id))

    return render_template('update.html', form=form)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  -->
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{%block styles %}
  {{super()}}
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%}
{% block content %}
    <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html' as macro%}
<!-- Content block -->

{%block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='index.css')}}">
{%endblock%}

{%block content%}
<div id="home" style="padding-top: 50px; padding-bottom: 80px;">
  <div class="container text-center" style="padding-bottom: 20px;"><br><br>
    <a href="{{url_for('main.new_post')}}" class="btn btn-warning"><b>Create Blog</b></a>
  </div>

<div class="container text-center">
  <h1><b>Recent Blogs</b></h1>
  <!-- <a href="/subscribe/{{current_user.id}}" class="btn btn-warning">Subscribe</a> -->
  <hr>
  {{macro.displayPosts(posts)}}
</div>
</div>

{%endblock%}

app/templates/macros.html
{% macro displayPosts(post_list)%}
    {%for post in post_list%}
    <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
        <div class="well well-lg" style="color: black;">
            <h4>{{post.title}}</h4>
            <p>{{post.text| truncate(120)}}</p>
            <p>Posted on: {{post.date_posted.strftime('%Y-%m-%d')}} <a href="/post/{{post.id}}" class="btn btn-info pull-right">More</a></p>

        </div>
    </div>
    {%endfor%}
{%endmacro%}

app/templates/navbar.html
<nav class="navbar navbar-light" style="margin: 0px;color: white; background-color: black;">
    <!-- <nav class="navbar navbar-inverse"> -->
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand"><b>PAYONEER BLOG</b> </a>
        </div>
        <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
                    <li><a href="{{url_for('main.all_posts')}}">Blogs</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{current_user.username| capitalize}} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            {% if current_user.role_id == 1 %}
                            <li><a href="{{url_for('main.new_post')}}">Create Post</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{{url_for('auth.logout')}}">Logout</a></li>
                            <!-- {%else%}
                            <li><a href="{{url_for('auth.logout')}}">Sign out</a></li> -->
                            {%endif%}

                        </ul>
                    </li>
                    {% else %}
                    <li><a href="{{url_for('auth.login')}}">Login</a></li>
                    <li><a href="{{url_for('auth.register')}}">Sign Up</a></li>
                </ul>
                {%endif%}
            </div>
    </div>
</div>
</nav>

app/templates/new_post.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container text-center btn-warning">
        <div class="col-md-10">
            <h3><b>Create a Blog</b></h3>
            <hr>
            {{ wtf.quick_form(post_form) }}
        </div>

    </div>

{% endblock %}

app/templates/post.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% import "bootstrap/wtf.html" as wtf %}

{%block styles%}
    {{ super() }}
{%endblock%}
<!-- Content block -->
{%block content%}
<div class="container text-center btn-info" style="color: black;">
    <div class="row">
        <h3>{{post.title}}</h3>
        <hr>
        <p>{{post.text}}</p>
        <span>
        <p>Posted on {{post.date_posted.strftime('%Y-%m-%d')}}</p>
        {% if current_user.is_authenticated%}
            <a href="{{url_for('main.delete_post',id = post.id)}}" class="btn btn-danger btn-sm">Delete</a>
            <a href="/post/update/{{post.id}}" class="btn btn-success btn-sm">Review</a>
        {%endif%}
    </div>
    <div class="row">
        <h4><b>Comments</b></h4>
        <hr>
        {% if current_user.is_authenticated %}
            {{ wtf.quick_form(form) }}
        {%endif%}
        {%for comment in comments%}
            <div class="col-md-10">
                <h5>{{comment.user.username}}</h5>
                <p>{{comment.comment}}</p>
                {% if current_user.is_authenticated%}
                    <a href="{{url_for('main.delete_comment',id = comment.id,post_id = comment.post)}}" class="btn btn-danger btn-sm">Delete</a>
                {%endif%}
            </div>
        {%endfor%}
    </div>
</div>
{%endblock%}

app/templates/posts.html
{% extends 'base.html' %}
{% import 'macros.html' as macro%}
<!-- Content block -->

{%block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='index.css')}}">
{%endblock%}

<!-- Content block -->
{%block content%}
<div id="nature" style="padding-top: 50px; padding-bottom: 80px;">
<div class="container text-center">
    <h1><b>All Blogs</b></h1>
    <hr>
    {{macro.displayPosts(posts)}}
</div>
</div>
{%endblock%}

app/templates/update.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container text-center btn-success">
        <div class="col-md-10">
            <h3><b>Update Blog</b></h3>
            <hr>
            {{ wtf.quick_form(form) }}
        </div>

    </div>

{% endblock %}